# Generated by Django 2.0.6 on 2018-06-09 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('basic_link', models.CharField(max_length=228)),
            ],
        ),
    ]
