# Generated by Django 2.0.6 on 2018-06-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_link_visited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='id',
            new_name='short_link',
        ),
    ]
