# Generated by Django 2.0.6 on 2018-06-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0004_auto_20180616_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='short_id',
            new_name='id',
        ),
    ]
