# Generated by Django 2.0.6 on 2018-06-20 15:38

from django.db import migrations

#apps - all aps from django, schema_editor - to edit theme
def migrate_tasks(apps, schema_editor):
    task = apps.get_model('shortlink', 'Link')
    task.objects.create(basic_link="https://github.com/KayafasKain/djangoshory")
    task.objects.create(basic_link="https://docs.djangoproject.com/en/2.0/ref/class-based-views/generic-editing/#django.views.generic.edit.CreateView")

class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0006_auto_20180616_1551'),
    ]
    '''function on rollback migration goes here as a parameter'''
    operations = [
        migrations.RunPython(
            migrate_tasks,
            migrations.RunPython.noop)
    ]
